#!/usr/bin/env python3
"""
________________________________________________________________________

:PROJECT: sila_cetoni

*neMESYS client*

:details: neMESYS:
    This is a sample service for controlling neMESYS syringe pumps via SiLA2

:file:    PumpDriveControlService_client.py
:authors: Florian Meinicke

:date: (creation)          2021-07-11T07:37:45.004830
:date: (last modification) 2021-07-11T07:37:45.004830

.. note:: Code generated by sila2codegenerator 0.3.6

_______________________________________________________________________

**Copyright**:
  This file is provided "AS IS" with NO WARRANTY OF ANY KIND,
  INCLUDING THE WARRANTIES OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

  For further Information see LICENSE file that comes with this distribution.
________________________________________________________________________
"""
__version__ = "0.1.0"

# import general packages
import logging
import argparse
import grpc
import time
import datetime

# import meta packages
from typing import Union, Optional

# import SiLA2 library modules
from sila2lib.framework import SiLAFramework_pb2 as silaFW_pb2
from sila2lib.sila_client import SiLA2Client
from sila2lib.framework.std_features import SiLAService_pb2 as SiLAService_feature_pb2
from sila2lib.error_handling import client_err
from sila2lib.error_handling.client_err import SiLAClientError
import sila2lib.utils.py2sila_types as p2s
#   Usually not needed, but - feel free to modify
# from sila2lib.framework.std_features import SimulationController_pb2 as SimController_feature_pb2

# import feature gRPC modules
# Import gRPC libraries of features
from .gRPC import PumpDriveControlService_pb2
from .gRPC import PumpDriveControlService_pb2_grpc
# import default arguments for this feature
from .PumpDriveControlService_default_arguments import default_dict as PumpDriveControlService_default_dict


# noinspection PyPep8Naming, PyUnusedLocal
class PumpDriveControlServiceClient:
    """
        This is a sample service for controlling neMESYS syringe pumps via SiLA2

    .. note:: For an example on how to construct the parameter or read the response(s) for command calls and properties,
              compare the default dictionary that is stored in the directory of the corresponding feature.
    """
    # The following variables will be filled when run() is executed
    #: Storage for the connected servers version
    server_version: str = ''
    #: Storage for the display name of the connected server
    server_display_name: str = ''
    #: Storage for the description of the connected server
    server_description: str = ''

    def __init__(self,
                 channel = None):
        """Class initialiser"""

        # Create stub objects used to communicate with the server
        self.PumpDriveControlService_stub = \
            PumpDriveControlService_pb2_grpc.PumpDriveControlServiceStub(channel)


        # initialise class variables for server information storage
        self.server_version = ''
        self.server_display_name = ''
        self.server_description = ''

    def InitializePumpDrive(self): # -> (PumpDriveControlService):
        """
        Wrapper to call the unobservable command InitializePumpDrive on the server.

        :returns: A gRPC object with the response that has been defined for this command.
        """
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Calling InitializePumpDrive:")
        try:
            response = self.PumpDriveControlService_stub.InitializePumpDrive(
                parameter = PumpDriveControlService_pb2.InitializePumpDrive_Parameters()
            )
            logging.debug(f"InitializePumpDrive response: {response}")

        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return


    def EnablePumpDrive(self): # -> (PumpDriveControlService):
        """
        Wrapper to call the unobservable command EnablePumpDrive on the server.

        :returns: A gRPC object with the response that has been defined for this command.
        """
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        parameter = None
        metadata = None  # add metadata generator here

        logging.debug("Calling EnablePumpDrive:")
        try:
            response = self.PumpDriveControlService_stub.EnablePumpDrive(
                PumpDriveControlService_pb2.EnablePumpDrive_Parameters()
            )
            logging.debug(f"EnablePumpDrive response: {response}")

        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return


    def DisablePumpDrive(self): # -> (PumpDriveControlService):
        """
        Wrapper to call the unobservable command DisablePumpDrive on the server.

        :returns: A gRPC object with the response that has been defined for this command.
        """
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        parameter = None
        metadata = None  # add metadata generator here

        logging.debug("Calling DisablePumpDrive:")
        try:
            response = self.PumpDriveControlService_stub.DisablePumpDrive(
                PumpDriveControlService_pb2.DisablePumpDrive_Parameters()
            )
            logging.debug(f"DisablePumpDrive response: {response}")

        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return



    def Subscribe_PumpDriveState(self) \
            -> PumpDriveControlService_pb2.Subscribe_PumpDriveState_Responses:
        """Wrapper to get property PumpDriveState from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading observable property PumpDriveState:")
        try:
            response = self.PumpDriveControlService_stub.Subscribe_PumpDriveState(
                PumpDriveControlService_pb2.Subscribe_PumpDriveState_Parameters()
            )
            logging.debug(
                'Subscribe_PumpDriveState response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response

    def Subscribe_FaultState(self) \
            -> PumpDriveControlService_pb2.Subscribe_FaultState_Responses:
        """Wrapper to get property FaultState from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading observable property FaultState:")
        try:
            response = self.PumpDriveControlService_stub.Subscribe_FaultState(
                PumpDriveControlService_pb2.Subscribe_FaultState_Parameters()
            )
            logging.debug(
                'Subscribe_FaultState response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response


    #   No metadata defined

    @staticmethod
    def grpc_error_handling(error_object: grpc.Call) -> None:
        """Handles exceptions of type grpc.RpcError"""
        # pass to the default error handling
        grpc_error =  client_err.grpc_error_handling(error_object=error_object)

        logging.error(grpc_error.error_type)
        if hasattr(grpc_error.message, "parameter"):
            logging.error(grpc_error.message.parameter)
        logging.error(grpc_error.message.message)
        if grpc_error.error_type == client_err.SiLAError.DEFINED_EXECUTION_ERROR:
          if grpc_error.message.errorIdentifier == 'InitializationFailed' :
            raise InitializationFailedError(grpc_error.message.message)


class InitializationFailedError(SiLAClientError):
    """Initialization Failed
    """
    pass


