# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AnalogOutChannelController.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sila2lib.framework.SiLAFramework_pb2 as SiLAFramework__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AnalogOutChannelController.proto',
  package='sila2.de.cetoni.io.analogoutchannelcontroller.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n AnalogOutChannelController.proto\x12\x30sila2.de.cetoni.io.analogoutchannelcontroller.v1\x1a\x13SiLAFramework.proto\"H\n\x19SetOutputValue_Parameters\x12+\n\x05Value\x18\x01 \x01(\x0b\x32\x1c.sila2.org.silastandard.Real\"\x1a\n\x18SetOutputValue_Responses\"\x1c\n\x1aSubscribe_Value_Parameters\"H\n\x19Subscribe_Value_Responses\x12+\n\x05Value\x18\x01 \x01(\x0b\x32\x1c.sila2.org.silastandard.Real2\xfd\x02\n\x1a\x41nalogOutChannelController\x12\xab\x01\n\x0eSetOutputValue\x12K.sila2.de.cetoni.io.analogoutchannelcontroller.v1.SetOutputValue_Parameters\x1aJ.sila2.de.cetoni.io.analogoutchannelcontroller.v1.SetOutputValue_Responses\"\x00\x12\xb0\x01\n\x0fSubscribe_Value\x12L.sila2.de.cetoni.io.analogoutchannelcontroller.v1.Subscribe_Value_Parameters\x1aK.sila2.de.cetoni.io.analogoutchannelcontroller.v1.Subscribe_Value_Responses\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[SiLAFramework__pb2.DESCRIPTOR,])




_SETOUTPUTVALUE_PARAMETERS = _descriptor.Descriptor(
  name='SetOutputValue_Parameters',
  full_name='sila2.de.cetoni.io.analogoutchannelcontroller.v1.SetOutputValue_Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Value', full_name='sila2.de.cetoni.io.analogoutchannelcontroller.v1.SetOutputValue_Parameters.Value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=179,
)


_SETOUTPUTVALUE_RESPONSES = _descriptor.Descriptor(
  name='SetOutputValue_Responses',
  full_name='sila2.de.cetoni.io.analogoutchannelcontroller.v1.SetOutputValue_Responses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=207,
)


_SUBSCRIBE_VALUE_PARAMETERS = _descriptor.Descriptor(
  name='Subscribe_Value_Parameters',
  full_name='sila2.de.cetoni.io.analogoutchannelcontroller.v1.Subscribe_Value_Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=237,
)


_SUBSCRIBE_VALUE_RESPONSES = _descriptor.Descriptor(
  name='Subscribe_Value_Responses',
  full_name='sila2.de.cetoni.io.analogoutchannelcontroller.v1.Subscribe_Value_Responses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Value', full_name='sila2.de.cetoni.io.analogoutchannelcontroller.v1.Subscribe_Value_Responses.Value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=311,
)

_SETOUTPUTVALUE_PARAMETERS.fields_by_name['Value'].message_type = SiLAFramework__pb2._REAL
_SUBSCRIBE_VALUE_RESPONSES.fields_by_name['Value'].message_type = SiLAFramework__pb2._REAL
DESCRIPTOR.message_types_by_name['SetOutputValue_Parameters'] = _SETOUTPUTVALUE_PARAMETERS
DESCRIPTOR.message_types_by_name['SetOutputValue_Responses'] = _SETOUTPUTVALUE_RESPONSES
DESCRIPTOR.message_types_by_name['Subscribe_Value_Parameters'] = _SUBSCRIBE_VALUE_PARAMETERS
DESCRIPTOR.message_types_by_name['Subscribe_Value_Responses'] = _SUBSCRIBE_VALUE_RESPONSES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetOutputValue_Parameters = _reflection.GeneratedProtocolMessageType('SetOutputValue_Parameters', (_message.Message,), {
  'DESCRIPTOR' : _SETOUTPUTVALUE_PARAMETERS,
  '__module__' : 'AnalogOutChannelController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.io.analogoutchannelcontroller.v1.SetOutputValue_Parameters)
  })
_sym_db.RegisterMessage(SetOutputValue_Parameters)

SetOutputValue_Responses = _reflection.GeneratedProtocolMessageType('SetOutputValue_Responses', (_message.Message,), {
  'DESCRIPTOR' : _SETOUTPUTVALUE_RESPONSES,
  '__module__' : 'AnalogOutChannelController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.io.analogoutchannelcontroller.v1.SetOutputValue_Responses)
  })
_sym_db.RegisterMessage(SetOutputValue_Responses)

Subscribe_Value_Parameters = _reflection.GeneratedProtocolMessageType('Subscribe_Value_Parameters', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBE_VALUE_PARAMETERS,
  '__module__' : 'AnalogOutChannelController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.io.analogoutchannelcontroller.v1.Subscribe_Value_Parameters)
  })
_sym_db.RegisterMessage(Subscribe_Value_Parameters)

Subscribe_Value_Responses = _reflection.GeneratedProtocolMessageType('Subscribe_Value_Responses', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBE_VALUE_RESPONSES,
  '__module__' : 'AnalogOutChannelController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.io.analogoutchannelcontroller.v1.Subscribe_Value_Responses)
  })
_sym_db.RegisterMessage(Subscribe_Value_Responses)



_ANALOGOUTCHANNELCONTROLLER = _descriptor.ServiceDescriptor(
  name='AnalogOutChannelController',
  full_name='sila2.de.cetoni.io.analogoutchannelcontroller.v1.AnalogOutChannelController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=314,
  serialized_end=695,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetOutputValue',
    full_name='sila2.de.cetoni.io.analogoutchannelcontroller.v1.AnalogOutChannelController.SetOutputValue',
    index=0,
    containing_service=None,
    input_type=_SETOUTPUTVALUE_PARAMETERS,
    output_type=_SETOUTPUTVALUE_RESPONSES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe_Value',
    full_name='sila2.de.cetoni.io.analogoutchannelcontroller.v1.AnalogOutChannelController.Subscribe_Value',
    index=1,
    containing_service=None,
    input_type=_SUBSCRIBE_VALUE_PARAMETERS,
    output_type=_SUBSCRIBE_VALUE_RESPONSES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALOGOUTCHANNELCONTROLLER)

DESCRIPTOR.services_by_name['AnalogOutChannelController'] = _ANALOGOUTCHANNELCONTROLLER

# @@protoc_insertion_point(module_scope)
