# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import AnalogInChannelProvider_pb2 as AnalogInChannelProvider__pb2


class AnalogInChannelProviderStub(object):
    """Feature: Analog In Channel Provider
    Allows to control one analog in channel of an I/O module
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe_Value = channel.unary_stream(
                '/sila2.de.cetoni.io.analoginchannelprovider.v1.AnalogInChannelProvider/Subscribe_Value',
                request_serializer=AnalogInChannelProvider__pb2.Subscribe_Value_Parameters.SerializeToString,
                response_deserializer=AnalogInChannelProvider__pb2.Subscribe_Value_Responses.FromString,
                )


class AnalogInChannelProviderServicer(object):
    """Feature: Analog In Channel Provider
    Allows to control one analog in channel of an I/O module
    """

    def Subscribe_Value(self, request, context):
        """Value
        The value of the analog I/O channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalogInChannelProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe_Value': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe_Value,
                    request_deserializer=AnalogInChannelProvider__pb2.Subscribe_Value_Parameters.FromString,
                    response_serializer=AnalogInChannelProvider__pb2.Subscribe_Value_Responses.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sila2.de.cetoni.io.analoginchannelprovider.v1.AnalogInChannelProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnalogInChannelProvider(object):
    """Feature: Analog In Channel Provider
    Allows to control one analog in channel of an I/O module
    """

    @staticmethod
    def Subscribe_Value(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sila2.de.cetoni.io.analoginchannelprovider.v1.AnalogInChannelProvider/Subscribe_Value',
            AnalogInChannelProvider__pb2.Subscribe_Value_Parameters.SerializeToString,
            AnalogInChannelProvider__pb2.Subscribe_Value_Responses.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
