#!/usr/bin/env python3
"""
________________________________________________________________________

:PROJECT: sila_cetoni

*Contiflow client*

:details: Contiflow:
    Allows to control a continuous flow pump that is made up of two syringe pumps

:file:    ContinuousFlowConfigurationService_client.py
:authors: Florian Meinicke

:date: (creation)          2021-07-10T10:33:25.043981
:date: (last modification) 2021-07-10T10:33:25.043981

.. note:: Code generated by sila2codegenerator 0.3.6

_______________________________________________________________________

**Copyright**:
  This file is provided "AS IS" with NO WARRANTY OF ANY KIND,
  INCLUDING THE WARRANTIES OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

  For further Information see LICENSE file that comes with this distribution.
________________________________________________________________________
"""
__version__ = "0.1.0"

# import general packages
import logging
import argparse
import grpc
import time
import datetime

# import meta packages
from typing import Union, Optional

# import SiLA2 library modules
from sila2lib.framework import SiLAFramework_pb2 as silaFW_pb2
from sila2lib.sila_client import SiLA2Client
from sila2lib.framework.std_features import SiLAService_pb2 as SiLAService_feature_pb2
from sila2lib.error_handling import client_err
from sila2lib.error_handling.client_err import SiLAClientError
import sila2lib.utils.py2sila_types as p2s
#   Usually not needed, but - feel free to modify
# from sila2lib.framework.std_features import SimulationController_pb2 as SimController_feature_pb2

# import feature gRPC modules
# Import gRPC libraries of features
from .gRPC import ContinuousFlowConfigurationService_pb2
from .gRPC import ContinuousFlowConfigurationService_pb2_grpc
# import default arguments for this feature
from .ContinuousFlowConfigurationService_default_arguments import default_dict as ContinuousFlowConfigurationService_default_dict


# noinspection PyPep8Naming, PyUnusedLocal
class ContinuousFlowConfigurationServiceClient:
    """
        Allows to control a continuous flow pump that is made up of two syringe pumps

    .. note:: For an example on how to construct the parameter or read the response(s) for command calls and properties,
              compare the default dictionary that is stored in the directory of the corresponding feature.
    """
    # The following variables will be filled when run() is executed
    #: Storage for the connected servers version
    server_version: str = ''
    #: Storage for the display name of the connected server
    server_display_name: str = ''
    #: Storage for the description of the connected server
    server_description: str = ''

    def __init__(self,
                 channel = None):
        """Class initialiser"""

        # Create stub objects used to communicate with the server
        self.ContinuousFlowConfigurationService_stub = \
            ContinuousFlowConfigurationService_pb2_grpc.ContinuousFlowConfigurationServiceStub(channel)


        # initialise class variables for server information storage
        self.server_version = ''
        self.server_display_name = ''
        self.server_description = ''

    def SetSwitchingMode(self, SwitchingMode: str): # -> (ContinuousFlowConfigurationService):
        """
        Wrapper to call the unobservable command SetSwitchingMode on the server.

        :param SwitchingMode: The new switching mode to set

        :returns: A gRPC object with the response that has been defined for this command.
        """
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Calling SetSwitchingMode:")
        try:
            parameter = ContinuousFlowConfigurationService_pb2.SetSwitchingMode_Parameters(
                SwitchingMode=silaFW_pb2.String(value=SwitchingMode)
            )

            response = self.ContinuousFlowConfigurationService_stub.SetSwitchingMode(parameter)
            logging.debug(f"SetSwitchingMode response: {response}")

        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return


    def SetRefillFlowRate(self, RefillFlowRate: float): # -> (ContinuousFlowConfigurationService):
        """
        Wrapper to call the unobservable command SetRefillFlowRate on the server.

        :param RefillFlowRate: The refill flow rate to set

        :returns: A gRPC object with the response that has been defined for this command.
        """
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Calling SetRefillFlowRate:")
        try:
            parameter = ContinuousFlowConfigurationService_pb2.SetRefillFlowRate_Parameters(
                RefillFlowRate=silaFW_pb2.Real(value=RefillFlowRate)
            )

            response = self.ContinuousFlowConfigurationService_stub.SetRefillFlowRate(parameter)
            logging.debug(f"SetRefillFlowRate response: {response}")

        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return


    def SetCrossFlowDuration(self, CrossFlowDuration: float): # -> (ContinuousFlowConfigurationService):
        """
        Wrapper to call the unobservable command SetCrossFlowDuration on the server.

        :param CrossFlowDuration: The cross flow duration to set

        :returns: A gRPC object with the response that has been defined for this command.
        """
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Calling SetCrossFlowDuration:")
        try:
            parameter = ContinuousFlowConfigurationService_pb2.SetCrossFlowDuration_Parameters(
                CrossFlowDuration=silaFW_pb2.Real(value=CrossFlowDuration)
            )

            response = self.ContinuousFlowConfigurationService_stub.SetCrossFlowDuration(parameter)
            logging.debug(f"SetCrossFlowDuration response: {response}")

        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return


    def SetOverlapDuration(self, OverlapDuration: float): # -> (ContinuousFlowConfigurationService):
        """
        Wrapper to call the unobservable command SetOverlapDuration on the server.

        :param OverlapDuration: The overlap duration to set

        :returns: A gRPC object with the response that has been defined for this command.
        """
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Calling SetOverlapDuration:")
        try:
            parameter = ContinuousFlowConfigurationService_pb2.SetOverlapDuration_Parameters(
                OverlapDuration=silaFW_pb2.Real(value=OverlapDuration)
            )

            response = self.ContinuousFlowConfigurationService_stub.SetOverlapDuration(parameter)
            logging.debug(f"SetOverlapDuration response: {response}")

        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return



    def Subscribe_SwitchingMode(self) \
            -> ContinuousFlowConfigurationService_pb2.Subscribe_SwitchingMode_Responses:
        """Wrapper to get property SwitchingMode from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading observable property SwitchingMode:")
        try:
            response = self.ContinuousFlowConfigurationService_stub.Subscribe_SwitchingMode(
                ContinuousFlowConfigurationService_pb2.Subscribe_SwitchingMode_Parameters()
            )
            logging.debug(
                'Subscribe_SwitchingMode response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response

    def Subscribe_MaxRefillFlowRate(self) \
            -> ContinuousFlowConfigurationService_pb2.Subscribe_MaxRefillFlowRate_Responses:
        """Wrapper to get property MaxRefillFlowRate from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading observable property MaxRefillFlowRate:")
        try:
            response = self.ContinuousFlowConfigurationService_stub.Subscribe_MaxRefillFlowRate(
                ContinuousFlowConfigurationService_pb2.Subscribe_MaxRefillFlowRate_Parameters()
            )
            logging.debug(
                'Subscribe_MaxRefillFlowRate response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response

    def Subscribe_RefillFlowRate(self) \
            -> ContinuousFlowConfigurationService_pb2.Subscribe_RefillFlowRate_Responses:
        """Wrapper to get property RefillFlowRate from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading observable property RefillFlowRate:")
        try:
            response = self.ContinuousFlowConfigurationService_stub.Subscribe_RefillFlowRate(
                ContinuousFlowConfigurationService_pb2.Subscribe_RefillFlowRate_Parameters()
            )
            logging.debug(
                'Subscribe_RefillFlowRate response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response

    def Subscribe_MinFlowRate(self) \
            -> ContinuousFlowConfigurationService_pb2.Subscribe_MinFlowRate_Responses:
        """Wrapper to get property MinFlowRate from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading observable property MinFlowRate:")
        try:
            response = self.ContinuousFlowConfigurationService_stub.Subscribe_MinFlowRate(
                ContinuousFlowConfigurationService_pb2.Subscribe_MinFlowRate_Parameters()
            )
            logging.debug(
                'Subscribe_MinFlowRate response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response

    def Subscribe_CrossFlowDuration(self) \
            -> ContinuousFlowConfigurationService_pb2.Subscribe_CrossFlowDuration_Responses:
        """Wrapper to get property CrossFlowDuration from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading observable property CrossFlowDuration:")
        try:
            response = self.ContinuousFlowConfigurationService_stub.Subscribe_CrossFlowDuration(
                ContinuousFlowConfigurationService_pb2.Subscribe_CrossFlowDuration_Parameters()
            )
            logging.debug(
                'Subscribe_CrossFlowDuration response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response

    def Subscribe_OverlapDuration(self) \
            -> ContinuousFlowConfigurationService_pb2.Subscribe_OverlapDuration_Responses:
        """Wrapper to get property OverlapDuration from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading observable property OverlapDuration:")
        try:
            response = self.ContinuousFlowConfigurationService_stub.Subscribe_OverlapDuration(
                ContinuousFlowConfigurationService_pb2.Subscribe_OverlapDuration_Parameters()
            )
            logging.debug(
                'Subscribe_OverlapDuration response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response


    #   No metadata defined

    @staticmethod
    def grpc_error_handling(error_object: grpc.Call) -> None:
        """Handles exceptions of type grpc.RpcError"""
        # pass to the default error handling
        grpc_error =  client_err.grpc_error_handling(error_object=error_object)

        logging.error(grpc_error.error_type)
        if hasattr(grpc_error.message, "parameter"):
            logging.error(grpc_error.message.parameter)
        logging.error(grpc_error.message.message)


