#!/usr/bin/env python3
"""
________________________________________________________________________

:PROJECT: sila_cetoni

*QmixIO client*

:details: QmixIO:
    The SiLA 2 driver for Qmix I/O Devices

:file:    DigitalOutChannelController_client.py
:authors: Florian Meinicke

:date: (creation)          2021-07-08T12:11:17.614614
:date: (last modification) 2021-07-08T12:11:17.614614

.. note:: Code generated by sila2codegenerator 0.3.6

_______________________________________________________________________

**Copyright**:
  This file is provided "AS IS" with NO WARRANTY OF ANY KIND,
  INCLUDING THE WARRANTIES OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

  For further Information see LICENSE file that comes with this distribution.
________________________________________________________________________
"""
__version__ = "0.1.0"

# import general packages
import logging
import argparse
import grpc
import time
import datetime

# import meta packages
from typing import Union, Optional

# import SiLA2 library modules
from sila2lib.framework import SiLAFramework_pb2 as silaFW_pb2
from sila2lib.sila_client import SiLA2Client
from sila2lib.framework.std_features import SiLAService_pb2 as SiLAService_feature_pb2
from sila2lib.error_handling import client_err
from sila2lib.error_handling.client_err import SiLAClientError
import sila2lib.utils.py2sila_types as p2s
#   Usually not needed, but - feel free to modify
# from sila2lib.framework.std_features import SimulationController_pb2 as SimController_feature_pb2

# import feature gRPC modules
# Import gRPC libraries of features
from .gRPC import DigitalOutChannelController_pb2
from .gRPC import DigitalOutChannelController_pb2_grpc
# import default arguments for this feature
from .DigitalOutChannelController_default_arguments import default_dict as DigitalOutChannelController_default_dict

from impl.common.decorators import channel_index_serializer

from . import METADATA_CHANNEL_INDEX

# noinspection PyPep8Naming, PyUnusedLocal
@channel_index_serializer(DigitalOutChannelController_pb2)
class DigitalOutChannelControllerClient:
    """
        The SiLA 2 driver for Qmix I/O Devices

    .. note:: For an example on how to construct the parameter or read the response(s) for command calls and properties,
              compare the default dictionary that is stored in the directory of the corresponding feature.
    """
    # The following variables will be filled when run() is executed
    #: Storage for the connected servers version
    server_version: str = ''
    #: Storage for the display name of the connected server
    server_display_name: str = ''
    #: Storage for the description of the connected server
    server_description: str = ''

    def __init__(self,
                 channel = None):
        """Class initialiser"""

        # Create stub objects used to communicate with the server
        self.DigitalOutChannelController_stub = \
            DigitalOutChannelController_pb2_grpc.DigitalOutChannelControllerStub(channel)


        # initialise class variables for server information storage
        self.server_version = ''
        self.server_display_name = ''
        self.server_description = ''

    def SetOutput(self, channel_id: int, State: str = 'On'): # -> (DigitalOutChannelController):
        """
        Wrapper to call the unobservable command SetOutput on the server.

        :param channel_id: The index of the controller channel to use (this value is 0-indexed)
                           Will be sent along as metadata of the call
        :param parameter: The parameter gRPC construct required for this command.

        :returns: A gRPC object with the response that has been defined for this command.
        """
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug(f"Calling SetOutput for channel {channel_id}:")
        try:
            parameter = DigitalOutChannelController_pb2.SetOutput_Parameters(
                State=DigitalOutChannelController_pb2.DataType_State(
                    State=silaFW_pb2.String(value=State)
                )
            )
            metadata = ((METADATA_CHANNEL_INDEX, self._serialize_channel_id(channel_id)),)

            response = self.DigitalOutChannelController_stub.SetOutput(parameter,metadata)
            logging.debug(f"SetOutput response: {response}")

        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return



    def Get_NumberOfChannels(self) \
            -> DigitalOutChannelController_pb2.Get_NumberOfChannels_Responses:
        """Wrapper to get property NumberOfChannels from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading unobservable property NumberOfChannels:")
        try:
            response = self.DigitalOutChannelController_stub.Get_NumberOfChannels(
                DigitalOutChannelController_pb2.Get_NumberOfChannels_Parameters()
            )
            logging.debug(
                'Get_NumberOfChannels response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response.NumberOfChannels

    def Subscribe_State(self, channel_id: int) \
            -> DigitalOutChannelController_pb2.Subscribe_State_Responses:
        """
        Wrapper to get property State from the server.

        :param channel_id: The index of the controller channel to use (this value is 0-indexed)
                           Will be sent along as metadata of the call
        """
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug(f"Reading observable property State for channel {channel_id}:")
        try:
            metadata = ((METADATA_CHANNEL_INDEX, self._serialize_channel_id(channel_id)),)
            response = self.DigitalOutChannelController_stub.Subscribe_State(
                DigitalOutChannelController_pb2.Subscribe_State_Parameters(),
                metadata
            )
            logging.debug(
                'Subscribe_State response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response


    def Get_FCPAffectedByMetadata_ChannelIndex(self) \
            -> DigitalOutChannelController_pb2.Get_FCPAffectedByMetadata_ChannelIndex_Responses:
        """Wrapper to get property FCPAffectedByMetadata_ChannelIndex from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading unobservable property FCPAffectedByMetadata_ChannelIndex:")
        try:
            response = self.DigitalOutChannelController_stub.Get_FCPAffectedByMetadata_ChannelIndex(
                DigitalOutChannelController_pb2.Get_FCPAffectedByMetadata_ChannelIndex_Parameters()
            )
            logging.debug(
                'Get_FCPAffectedByMetadata_ChannelIndex response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response.AffectedCalls



    @staticmethod
    def grpc_error_handling(error_object: grpc.Call) -> None:
        """Handles exceptions of type grpc.RpcError"""
        # pass to the default error handling
        grpc_error =  client_err.grpc_error_handling(error_object=error_object)

        logging.error(grpc_error.error_type)
        if hasattr(grpc_error.message, "parameter"):
            logging.error(grpc_error.message.parameter)
        logging.error(grpc_error.message.message)
        if grpc_error.error_type == client_err.SiLAError.DEFINED_EXECUTION_ERROR:
          if grpc_error.message.errorIdentifier == 'InvalidChannelIndex' :
            raise InvalidChannelIndexError(grpc_error.message.message)


class InvalidChannelIndexError(SiLAClientError):
    """Invalid Channel Index
    """
    pass


