#!/usr/bin/env python3
"""
________________________________________________________________________

:PROJECT: sila_cetoni

*Valve client*

:details: Valve:
    Allows to control valve devices

:file:    ValveGatewayService_client.py
:authors: Florian Meinicke

:date: (creation)          2021-07-10T09:27:04.773910
:date: (last modification) 2021-07-10T09:27:04.773910

.. note:: Code generated by sila2codegenerator 0.3.6

_______________________________________________________________________

**Copyright**:
  This file is provided "AS IS" with NO WARRANTY OF ANY KIND,
  INCLUDING THE WARRANTIES OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

  For further Information see LICENSE file that comes with this distribution.
________________________________________________________________________
"""
__version__ = "0.1.0"

# import general packages
import logging
import argparse
import grpc
import time
import datetime

# import meta packages
from typing import Union, Optional

# import SiLA2 library modules
from sila2lib.framework import SiLAFramework_pb2 as silaFW_pb2
from sila2lib.sila_client import SiLA2Client
from sila2lib.framework.std_features import SiLAService_pb2 as SiLAService_feature_pb2
from sila2lib.error_handling import client_err
from sila2lib.error_handling.client_err import SiLAClientError
import sila2lib.utils.py2sila_types as p2s
#   Usually not needed, but - feel free to modify
# from sila2lib.framework.std_features import SimulationController_pb2 as SimController_feature_pb2

# import feature gRPC modules
# Import gRPC libraries of features
from .gRPC import ValveGatewayService_pb2
from .gRPC import ValveGatewayService_pb2_grpc
# import default arguments for this feature
from .ValveGatewayService_default_arguments import default_dict as ValveGatewayService_default_dict


# noinspection PyPep8Naming, PyUnusedLocal
class ValveGatewayServiceClient:
    """
        Allows to control valve devices

    .. note:: For an example on how to construct the parameter or read the response(s) for command calls and properties,
              compare the default dictionary that is stored in the directory of the corresponding feature.
    """
    # The following variables will be filled when run() is executed
    #: Storage for the connected servers version
    server_version: str = ''
    #: Storage for the display name of the connected server
    server_display_name: str = ''
    #: Storage for the description of the connected server
    server_description: str = ''

    def __init__(self,
                 channel = None):
        """Class initialiser"""

        # Create stub objects used to communicate with the server
        self.ValveGatewayService_stub = \
            ValveGatewayService_pb2_grpc.ValveGatewayServiceStub(channel)


        # initialise class variables for server information storage
        self.server_version = ''
        self.server_display_name = ''
        self.server_description = ''



    def Get_NumberOfValves(self) \
            -> ValveGatewayService_pb2.Get_NumberOfValves_Responses:
        """Wrapper to get property NumberOfValves from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading unobservable property NumberOfValves:")
        try:
            response = self.ValveGatewayService_stub.Get_NumberOfValves(
                ValveGatewayService_pb2.Get_NumberOfValves_Parameters()
            )
            logging.debug(
                'Get_NumberOfValves response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response.NumberOfValves



    def Get_FCPAffectedByMetadata_ValveIndex(self) \
            -> ValveGatewayService_pb2.Get_FCPAffectedByMetadata_ValveIndex_Responses:
        """Wrapper to get property FCPAffectedByMetadata_ValveIndex from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading unobservable property FCPAffectedByMetadata_ValveIndex:")
        try:
            response = self.ValveGatewayService_stub.Get_FCPAffectedByMetadata_ValveIndex(
                ValveGatewayService_pb2.Get_FCPAffectedByMetadata_ValveIndex_Parameters()
            )
            logging.debug(
                'Get_FCPAffectedByMetadata_ValveIndex response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response.AffectedCalls



    @staticmethod
    def grpc_error_handling(error_object: grpc.Call) -> None:
        """Handles exceptions of type grpc.RpcError"""
        # pass to the default error handling
        grpc_error =  client_err.grpc_error_handling(error_object=error_object)

        logging.error(grpc_error.error_type)
        if hasattr(grpc_error.message, "parameter"):
            logging.error(grpc_error.message.parameter)
        logging.error(grpc_error.message.message)


