#!/usr/bin/env python3
"""
________________________________________________________________________

:PROJECT: sila_cetoni

*neMESYS client*

:details: neMESYS:
    This is a sample service for controlling neMESYS syringe pumps via SiLA2

:file:    SyringeConfigurationController_client.py
:authors: Florian Meinicke

:date: (creation)          2021-07-11T07:37:48.152112
:date: (last modification) 2021-07-11T07:37:48.152112

.. note:: Code generated by sila2codegenerator 0.3.6

_______________________________________________________________________

**Copyright**:
  This file is provided "AS IS" with NO WARRANTY OF ANY KIND,
  INCLUDING THE WARRANTIES OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

  For further Information see LICENSE file that comes with this distribution.
________________________________________________________________________
"""
__version__ = "0.1.0"

# import general packages
import logging
import argparse
import grpc
import time
import datetime

# import meta packages
from typing import Union, Optional

# import SiLA2 library modules
from sila2lib.framework import SiLAFramework_pb2 as silaFW_pb2
from sila2lib.sila_client import SiLA2Client
from sila2lib.framework.std_features import SiLAService_pb2 as SiLAService_feature_pb2
from sila2lib.error_handling import client_err
from sila2lib.error_handling.client_err import SiLAClientError
import sila2lib.utils.py2sila_types as p2s
#   Usually not needed, but - feel free to modify
# from sila2lib.framework.std_features import SimulationController_pb2 as SimController_feature_pb2

# import feature gRPC modules
# Import gRPC libraries of features
from .gRPC import SyringeConfigurationController_pb2
from .gRPC import SyringeConfigurationController_pb2_grpc
# import default arguments for this feature
from .SyringeConfigurationController_default_arguments import default_dict as SyringeConfigurationController_default_dict


# noinspection PyPep8Naming, PyUnusedLocal
class SyringeConfigurationControllerClient:
    """
        This is a sample service for controlling neMESYS syringe pumps via SiLA2

    .. note:: For an example on how to construct the parameter or read the response(s) for command calls and properties,
              compare the default dictionary that is stored in the directory of the corresponding feature.
    """
    # The following variables will be filled when run() is executed
    #: Storage for the connected servers version
    server_version: str = ''
    #: Storage for the display name of the connected server
    server_display_name: str = ''
    #: Storage for the description of the connected server
    server_description: str = ''

    def __init__(self,
                 channel = None):
        """Class initialiser"""

        # Create stub objects used to communicate with the server
        self.SyringeConfigurationController_stub = \
            SyringeConfigurationController_pb2_grpc.SyringeConfigurationControllerStub(channel)


        # initialise class variables for server information storage
        self.server_version = ''
        self.server_display_name = ''
        self.server_description = ''

    def SetSyringeParameters(self, InnerDiameter: float, MaxPistonStroke: float): # -> (SyringeConfigurationController):
        """
        Wrapper to call the unobservable command SetSyringeParameters on the server.

        :param InnerDiameter: Inner diameter of the syringe tube in millimetres
        :param MaxPistonStroke: The maximum piston stroke defines the maximum position
                                the piston can be moved to before it slips out of
                                the syringe tube. The maximum piston stroke limits
                                the maximum travel range of the syringe pump pusher.

        :returns: A gRPC object with the response that has been defined for this command.
        """
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Calling SetSyringeParameters:")
        try:
            parameter = SyringeConfigurationController_pb2.SetSyringeParameters_Parameters(
                InnerDiameter=silaFW_pb2.Real(value=InnerDiameter),
                MaxPistonStroke=silaFW_pb2.Real(value=MaxPistonStroke)
            )

            response = self.SyringeConfigurationController_stub.SetSyringeParameters(parameter)
            logging.debug(f"SetSyringeParameters response: {response}")

        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return



    def Subscribe_InnerDiameter(self) \
            -> SyringeConfigurationController_pb2.Subscribe_InnerDiameter_Responses:
        """Wrapper to get property InnerDiameter from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading observable property InnerDiameter:")
        try:
            response = self.SyringeConfigurationController_stub.Subscribe_InnerDiameter(
                SyringeConfigurationController_pb2.Subscribe_InnerDiameter_Parameters()
            )
            logging.debug(
                'Subscribe_InnerDiameter response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response

    def Subscribe_MaxPistonStroke(self) \
            -> SyringeConfigurationController_pb2.Subscribe_MaxPistonStroke_Responses:
        """Wrapper to get property MaxPistonStroke from the server."""
        # noinspection PyUnusedLocal - type definition, just for convenience
        grpc_err: grpc.Call

        logging.debug("Reading observable property MaxPistonStroke:")
        try:
            response = self.SyringeConfigurationController_stub.Subscribe_MaxPistonStroke(
                SyringeConfigurationController_pb2.Subscribe_MaxPistonStroke_Parameters()
            )
            logging.debug(
                'Subscribe_MaxPistonStroke response: {response}'.format(
                    response=response
                )
            )
        except grpc.RpcError as grpc_err:
            self.grpc_error_handling(grpc_err)
            return None

        return response


    #   No metadata defined

    @staticmethod
    def grpc_error_handling(error_object: grpc.Call) -> None:
        """Handles exceptions of type grpc.RpcError"""
        # pass to the default error handling
        grpc_error =  client_err.grpc_error_handling(error_object=error_object)

        logging.error(grpc_error.error_type)
        if hasattr(grpc_error.message, "parameter"):
            logging.error(grpc_error.message.parameter)
        logging.error(grpc_error.message.message)


