"""
________________________________________________________________________

:PROJECT: sila_cetoni

*Valve Position Controller_defined_errors*

:details: ValvePositionController Defined SiLA Error factories:
    Allows to specify a certain logical position for a valve. The Position property can be querried at any time to
    obtain the current valve position.

:file:    ValvePositionController_defined_errors.py
:authors: Florian Meinicke

:date: (creation)          2021-07-10T09:27:04.760906
:date: (last modification) 2021-07-10T09:27:04.760906

.. note:: Code generated by sila2codegenerator 0.3.6

________________________________________________________________________

**Copyright**:
  This file is provided "AS IS" with NO WARRANTY OF ANY KIND,
  INCLUDING THE WARRANTIES OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

  For further Information see LICENSE file that comes with this distribution.
________________________________________________________________________
"""

__version__ = "0.1.0"

# import general packages
from sila2lib.error_handling.server_err import SiLAExecutionError

# SiLA Defined Error factories


class ValveNotToggleableError(SiLAExecutionError):
    """
    The current valve does not support toggling because it has more than only two possible positions.
    """

    def __init__(self, extra_message: str = ""):
        """

        :param extra_message: extra message, that can be added to the default message
        """

        msg = "The current valve does not support toggling because it has more than only two possible positions." \
              + (f'\n{extra_message}' if extra_message else "")
        super().__init__(
            error_identifier="de.cetoni/valves/ValvePositionController/v1/DefinedError/ValveNotToggleable",
            msg=msg
        )

class ValvePositionNotAvailableError(SiLAExecutionError):
    """
    The actual position of the current valve cannot be retrieved. This is most
    likely a temporary error that can be fixed by setting a specific valve position.
    """

    def __init__(self, extra_message: str = ""):
        """

        :param extra_message: extra message, that can be added to the default message
        """

        msg = "The actual position of the current valve cannot be retrieved. " \
              "This is most likely a temporary error that can be fixed by setting a specific valve position." \
               + (f'\n{extra_message}' if extra_message else "")
        super().__init__(
            error_identifier="de.cetoni/valves/ValvePositionController/v1/DefinedError/ValvePositionNotAvailable",
            msg=msg
        )
