# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ValvePositionController.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sila2lib.framework.SiLAFramework_pb2 as SiLAFramework__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ValvePositionController.proto',
  package='sila2.de.cetoni.valves.valvepositioncontroller.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dValvePositionController.proto\x12\x31sila2.de.cetoni.valves.valvepositioncontroller.v1\x1a\x13SiLAFramework.proto\"P\n\x1bSwitchToPosition_Parameters\x12\x31\n\x08Position\x18\x01 \x01(\x0b\x32\x1f.sila2.org.silastandard.Integer\"\x1c\n\x1aSwitchToPosition_Responses\"\x1b\n\x19TogglePosition_Parameters\"\x1a\n\x18TogglePosition_Responses\"\"\n Get_NumberOfPositions_Parameters\"]\n\x1fGet_NumberOfPositions_Responses\x12:\n\x11NumberOfPositions\x18\x01 \x01(\x0b\x32\x1f.sila2.org.silastandard.Integer\"\x1f\n\x1dSubscribe_Position_Parameters\"Q\n\x1cSubscribe_Position_Responses\x12\x31\n\x08Position\x18\x01 \x01(\x0b\x32\x1f.sila2.org.silastandard.Integer2\x82\x06\n\x17ValvePositionController\x12\xb3\x01\n\x10SwitchToPosition\x12N.sila2.de.cetoni.valves.valvepositioncontroller.v1.SwitchToPosition_Parameters\x1aM.sila2.de.cetoni.valves.valvepositioncontroller.v1.SwitchToPosition_Responses\"\x00\x12\xad\x01\n\x0eTogglePosition\x12L.sila2.de.cetoni.valves.valvepositioncontroller.v1.TogglePosition_Parameters\x1aK.sila2.de.cetoni.valves.valvepositioncontroller.v1.TogglePosition_Responses\"\x00\x12\xc2\x01\n\x15Get_NumberOfPositions\x12S.sila2.de.cetoni.valves.valvepositioncontroller.v1.Get_NumberOfPositions_Parameters\x1aR.sila2.de.cetoni.valves.valvepositioncontroller.v1.Get_NumberOfPositions_Responses\"\x00\x12\xbb\x01\n\x12Subscribe_Position\x12P.sila2.de.cetoni.valves.valvepositioncontroller.v1.Subscribe_Position_Parameters\x1aO.sila2.de.cetoni.valves.valvepositioncontroller.v1.Subscribe_Position_Responses\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[SiLAFramework__pb2.DESCRIPTOR,])




_SWITCHTOPOSITION_PARAMETERS = _descriptor.Descriptor(
  name='SwitchToPosition_Parameters',
  full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.SwitchToPosition_Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Position', full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.SwitchToPosition_Parameters.Position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=185,
)


_SWITCHTOPOSITION_RESPONSES = _descriptor.Descriptor(
  name='SwitchToPosition_Responses',
  full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.SwitchToPosition_Responses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=215,
)


_TOGGLEPOSITION_PARAMETERS = _descriptor.Descriptor(
  name='TogglePosition_Parameters',
  full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.TogglePosition_Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=244,
)


_TOGGLEPOSITION_RESPONSES = _descriptor.Descriptor(
  name='TogglePosition_Responses',
  full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.TogglePosition_Responses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=272,
)


_GET_NUMBEROFPOSITIONS_PARAMETERS = _descriptor.Descriptor(
  name='Get_NumberOfPositions_Parameters',
  full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.Get_NumberOfPositions_Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=308,
)


_GET_NUMBEROFPOSITIONS_RESPONSES = _descriptor.Descriptor(
  name='Get_NumberOfPositions_Responses',
  full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.Get_NumberOfPositions_Responses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='NumberOfPositions', full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.Get_NumberOfPositions_Responses.NumberOfPositions', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=403,
)


_SUBSCRIBE_POSITION_PARAMETERS = _descriptor.Descriptor(
  name='Subscribe_Position_Parameters',
  full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.Subscribe_Position_Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=436,
)


_SUBSCRIBE_POSITION_RESPONSES = _descriptor.Descriptor(
  name='Subscribe_Position_Responses',
  full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.Subscribe_Position_Responses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Position', full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.Subscribe_Position_Responses.Position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=519,
)

_SWITCHTOPOSITION_PARAMETERS.fields_by_name['Position'].message_type = SiLAFramework__pb2._INTEGER
_GET_NUMBEROFPOSITIONS_RESPONSES.fields_by_name['NumberOfPositions'].message_type = SiLAFramework__pb2._INTEGER
_SUBSCRIBE_POSITION_RESPONSES.fields_by_name['Position'].message_type = SiLAFramework__pb2._INTEGER
DESCRIPTOR.message_types_by_name['SwitchToPosition_Parameters'] = _SWITCHTOPOSITION_PARAMETERS
DESCRIPTOR.message_types_by_name['SwitchToPosition_Responses'] = _SWITCHTOPOSITION_RESPONSES
DESCRIPTOR.message_types_by_name['TogglePosition_Parameters'] = _TOGGLEPOSITION_PARAMETERS
DESCRIPTOR.message_types_by_name['TogglePosition_Responses'] = _TOGGLEPOSITION_RESPONSES
DESCRIPTOR.message_types_by_name['Get_NumberOfPositions_Parameters'] = _GET_NUMBEROFPOSITIONS_PARAMETERS
DESCRIPTOR.message_types_by_name['Get_NumberOfPositions_Responses'] = _GET_NUMBEROFPOSITIONS_RESPONSES
DESCRIPTOR.message_types_by_name['Subscribe_Position_Parameters'] = _SUBSCRIBE_POSITION_PARAMETERS
DESCRIPTOR.message_types_by_name['Subscribe_Position_Responses'] = _SUBSCRIBE_POSITION_RESPONSES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SwitchToPosition_Parameters = _reflection.GeneratedProtocolMessageType('SwitchToPosition_Parameters', (_message.Message,), {
  'DESCRIPTOR' : _SWITCHTOPOSITION_PARAMETERS,
  '__module__' : 'ValvePositionController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.valves.valvepositioncontroller.v1.SwitchToPosition_Parameters)
  })
_sym_db.RegisterMessage(SwitchToPosition_Parameters)

SwitchToPosition_Responses = _reflection.GeneratedProtocolMessageType('SwitchToPosition_Responses', (_message.Message,), {
  'DESCRIPTOR' : _SWITCHTOPOSITION_RESPONSES,
  '__module__' : 'ValvePositionController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.valves.valvepositioncontroller.v1.SwitchToPosition_Responses)
  })
_sym_db.RegisterMessage(SwitchToPosition_Responses)

TogglePosition_Parameters = _reflection.GeneratedProtocolMessageType('TogglePosition_Parameters', (_message.Message,), {
  'DESCRIPTOR' : _TOGGLEPOSITION_PARAMETERS,
  '__module__' : 'ValvePositionController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.valves.valvepositioncontroller.v1.TogglePosition_Parameters)
  })
_sym_db.RegisterMessage(TogglePosition_Parameters)

TogglePosition_Responses = _reflection.GeneratedProtocolMessageType('TogglePosition_Responses', (_message.Message,), {
  'DESCRIPTOR' : _TOGGLEPOSITION_RESPONSES,
  '__module__' : 'ValvePositionController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.valves.valvepositioncontroller.v1.TogglePosition_Responses)
  })
_sym_db.RegisterMessage(TogglePosition_Responses)

Get_NumberOfPositions_Parameters = _reflection.GeneratedProtocolMessageType('Get_NumberOfPositions_Parameters', (_message.Message,), {
  'DESCRIPTOR' : _GET_NUMBEROFPOSITIONS_PARAMETERS,
  '__module__' : 'ValvePositionController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.valves.valvepositioncontroller.v1.Get_NumberOfPositions_Parameters)
  })
_sym_db.RegisterMessage(Get_NumberOfPositions_Parameters)

Get_NumberOfPositions_Responses = _reflection.GeneratedProtocolMessageType('Get_NumberOfPositions_Responses', (_message.Message,), {
  'DESCRIPTOR' : _GET_NUMBEROFPOSITIONS_RESPONSES,
  '__module__' : 'ValvePositionController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.valves.valvepositioncontroller.v1.Get_NumberOfPositions_Responses)
  })
_sym_db.RegisterMessage(Get_NumberOfPositions_Responses)

Subscribe_Position_Parameters = _reflection.GeneratedProtocolMessageType('Subscribe_Position_Parameters', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBE_POSITION_PARAMETERS,
  '__module__' : 'ValvePositionController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.valves.valvepositioncontroller.v1.Subscribe_Position_Parameters)
  })
_sym_db.RegisterMessage(Subscribe_Position_Parameters)

Subscribe_Position_Responses = _reflection.GeneratedProtocolMessageType('Subscribe_Position_Responses', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBE_POSITION_RESPONSES,
  '__module__' : 'ValvePositionController_pb2'
  # @@protoc_insertion_point(class_scope:sila2.de.cetoni.valves.valvepositioncontroller.v1.Subscribe_Position_Responses)
  })
_sym_db.RegisterMessage(Subscribe_Position_Responses)



_VALVEPOSITIONCONTROLLER = _descriptor.ServiceDescriptor(
  name='ValvePositionController',
  full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.ValvePositionController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=522,
  serialized_end=1292,
  methods=[
  _descriptor.MethodDescriptor(
    name='SwitchToPosition',
    full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.ValvePositionController.SwitchToPosition',
    index=0,
    containing_service=None,
    input_type=_SWITCHTOPOSITION_PARAMETERS,
    output_type=_SWITCHTOPOSITION_RESPONSES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TogglePosition',
    full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.ValvePositionController.TogglePosition',
    index=1,
    containing_service=None,
    input_type=_TOGGLEPOSITION_PARAMETERS,
    output_type=_TOGGLEPOSITION_RESPONSES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Get_NumberOfPositions',
    full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.ValvePositionController.Get_NumberOfPositions',
    index=2,
    containing_service=None,
    input_type=_GET_NUMBEROFPOSITIONS_PARAMETERS,
    output_type=_GET_NUMBEROFPOSITIONS_RESPONSES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe_Position',
    full_name='sila2.de.cetoni.valves.valvepositioncontroller.v1.ValvePositionController.Subscribe_Position',
    index=3,
    containing_service=None,
    input_type=_SUBSCRIBE_POSITION_PARAMETERS,
    output_type=_SUBSCRIBE_POSITION_RESPONSES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VALVEPOSITIONCONTROLLER)

DESCRIPTOR.services_by_name['ValvePositionController'] = _VALVEPOSITIONCONTROLLER

# @@protoc_insertion_point(module_scope)
