"""
________________________________________________________________________

:PROJECT: sila_cetoni

*Analog In Channel Provider*

:details: AnalogInChannelProvider:
    Allows to control one analog in channel of an I/O module

:file:    AnalogInChannelProvider_real.py
:authors: Florian Meinicke

:date: (creation)          2020-12-09T09:15:03.163511
:date: (last modification) 2020-12-09T09:15:03.163511

.. note:: Code generated by sila2codegenerator 0.2.0

________________________________________________________________________

**Copyright**:
  This file is provided "AS IS" with NO WARRANTY OF ANY KIND,
  INCLUDING THE WARRANTIES OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

  For further Information see LICENSE file that comes with this distribution.
________________________________________________________________________
"""

__version__ = "0.1.0"

# import general packages
import logging
import time         # used for observables
import uuid         # used for observables
import grpc         # used for type hinting only

# import SiLA2 library
import sila2lib.framework.SiLAFramework_pb2 as silaFW_pb2

# import gRPC modules for this feature
from .gRPC import AnalogInChannelProvider_pb2 as AnalogInChannelProvider_pb2
# from .gRPC import AnalogInChannelProvider_pb2_grpc as AnalogInChannelProvider_pb2_grpc

# import default arguments
from .AnalogInChannelProvider_default_arguments import default_dict

# import channel gateway feature
from impl.de.cetoni.core.ChannelGatewayService import ChannelGatewayService_servicer as ChannelGatewayService

# noinspection PyPep8Naming,PyUnusedLocal
class AnalogInChannelProviderReal:
    """
    Implementation of the *Analog In Channel Provider* in *Real* mode
        The SiLA 2 driver for Qmix I/O Devices
    """

    def __init__(self, channel_gateway: ChannelGatewayService):
        """
        Class initialiser

        :param channel_gateway: The ChannelGatewayService feature that provides
                                the channels that this feature can operate on
        """

        self.channel_gateway = channel_gateway

        logging.debug('Started server in mode: {mode}'.format(mode='Real'))

    def Subscribe_Value(self, request, context: grpc.ServicerContext) \
            -> AnalogInChannelProvider_pb2.Subscribe_Value_Responses:
        """
        Requests the observable property Value
            The value of the analog I/O channel.

        :param request: An empty gRPC request object (properties have no parameters)
        :param context: gRPC :class:`~grpc.ServicerContext` object providing gRPC-specific information

        :returns: A response object with the following fields:
            request.Value (Value): The value of the analog I/O channel.
        """

        channel = self.channel_gateway.get_channel(context.invocation_metadata(), "Property")

        while True:
            yield AnalogInChannelProvider_pb2.Subscribe_Value_Responses(
                Value=silaFW_pb2.Real(value=channel.read_input())
            )
            time.sleep(0.5) # give client some time to catch up
