"""
________________________________________________________________________

:PROJECT: sila_cetoni

*Analog In Channel Provider*

:details: AnalogInChannelProvider:
    Allows to control one analog input channel of an I/O module

:file:    AnalogInChannelProvider_simulation.py
:authors: Florian Meinicke

:date: (creation)          2020-12-09T09:15:03.162511
:date: (last modification) 2021-07-08T11:41:57.359184

.. note:: Code generated by sila2codegenerator 0.3.6

________________________________________________________________________

**Copyright**:
  This file is provided "AS IS" with NO WARRANTY OF ANY KIND,
  INCLUDING THE WARRANTIES OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

  For further Information see LICENSE file that comes with this distribution.
________________________________________________________________________
"""

__version__ = "0.1.0"

# import general packages
import logging
import time         # used for observables
import uuid         # used for observables
import grpc         # used for type hinting only

# import SiLA2 library
import sila2lib.framework.SiLAFramework_pb2 as silaFW_pb2

# import gRPC modules for this feature
from .gRPC import AnalogInChannelProvider_pb2 as AnalogInChannelProvider_pb2
# from .gRPC import AnalogInChannelProvider_pb2_grpc as AnalogInChannelProvider_pb2_grpc

# import default arguments
from .AnalogInChannelProvider_default_arguments import default_dict

# noinspection PyPep8Naming,PyUnusedLocal
class AnalogInChannelProviderSimulation:
    """
    Implementation of the *Analog In Channel Provider* in *Simulation* mode
        The SiLA 2 driver for Qmix I/O Devices
    """

    def __init__(self):
        """Class initialiser"""

        logging.debug('Started server in mode: {mode}'.format(mode='Simulation'))

    def Subscribe_Value(self, request, channel, context: grpc.ServicerContext) \
            -> AnalogInChannelProvider_pb2.Subscribe_Value_Responses:
        """
        Requests the observable property Value
            The value of the analog input channel.

        :param request: An empty gRPC request object (properties have no parameters)
        :param context: gRPC :class:`~grpc.ServicerContext` object providing gRPC-specific information

        :returns: A response object with the following fields:
            Value (Value): The value of the analog input channel.
        """

        # initialise the return value
        return_value: AnalogInChannelProvider_pb2.Subscribe_Value_Responses = None

        # we could use a timeout here if we wanted
        while True:
            # TODO:
            #   Add implementation of Simulation for property Value here and write the resulting
            #   response in return_value

            # create the default value
            if return_value is None:
                return_value = AnalogInChannelProvider_pb2.Subscribe_Value_Responses(
                    #**default_dict['Subscribe_Value_Responses']
                    Value=silaFW_pb2.Real(value=1.0)
                )


            yield return_value
