"""
________________________________________________________________________

:PROJECT: SiLA2_python

*Balance Service_defined_errors*

:details: BalanceService Defined SiLA Error factories:
    Provides an interface to a balance to read its current value and tare the balance if necessary

:file:    BalanceService_defined_errors.py
:authors: Florian Meinicke

:date: (creation)          2021-11-24T15:23:15.539560
:date: (last modification) 2021-11-24T15:23:15.539560

.. note:: Code generated by sila2codegenerator 0.3.7

________________________________________________________________________

**Copyright**:
  This file is provided "AS IS" with NO WARRANTY OF ANY KIND,
  INCLUDING THE WARRANTIES OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

  For further Information see LICENSE file that comes with this distribution.
________________________________________________________________________
"""

__version__ = "0.1.0"

# import general packages
from sila2lib.error_handling.server_err import SiLAExecutionError

# SiLA Defined Error factories

